runtime: php55
api_version: 1

handlers:

- url: /getNewPlurks
  script: app/getNewPlurks.php

- url: /processPlurk
  script: app/processPlurk.php

- url: /addNewFriend
  script: app/addNewFriend.php

###################################################

automatic_scaling:
  target_cpu_utilization: 0.95
  target_throughput_utilization: 0.95
  min_pending_latency: 250ms
  max_pending_latency: 750ms
  max_concurrent_requests: 30
  max_idle_instances: 0
