runtime: php72

handlers:

- url: /.*
  script: auto
  secure: always

#################################

automatic_scaling:
  target_cpu_utilization: 0.95
  target_throughput_utilization: 0.95
  min_pending_latency: 250ms
  max_pending_latency: 750ms
  max_concurrent_requests: 60
  max_idle_instances: 0
