runtime: php81

handlers:

- url: /logo\.png
  static_files: public/logo.png
  upload: public/logo\.png

- url: /.*
  script: auto
  secure: always

#################################

automatic_scaling:
  max_instances: 1
